### ISSUE TITLE
What all can this do?

### ISSUE THREAD

**Issue by TheColonel2688** [FrankPfattheicher/WagoLoader#2]
Its not clear to me after reading the readme what this project is for. 

Can I use this to 
- Update the Firmware
- Load the Codesys Control for PFC100 runtime
- Set IP address
- Load Codesys Application on to the device?

**Comment by FrankPfattheicher** [comment]
The tool is to deploy the user software to a new device.

(?) Update the Firmware
(!) No

(?) Load the Codesys Control for PFC100 runtime
(!) No

(?) Set IP address
(!) No

(?) Load Codesys Application on to the device
(!) Yes !

Aditionally
* Optionally set the system time and timezone
* Create linux and WBM users (with password)
